//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertaGrupo
    {
        public int ID { get; set; }
        public int Alerta_ID { get; set; }
        public int Grupo_ID { get; set; }
    
        public virtual Alerta Alerta { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
