//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public Alerta()
        {
            this.Evento = new HashSet<Evento>();
        }
    
        public int ID { get; set; }
        public string Titulo { get; set; }
        public System.DateTime FechaNotificacion { get; set; }
        public string HoraNotificacion { get; set; }
        public int Tipo { get; set; }
        public bool Activa { get; set; }
        public string Descripcion { get; set; }
        public string NombreProfesional { get; set; }
    
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
