//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public Alerta()
        {
            this.AlertaCaballo = new HashSet<AlertaCaballo>();
            this.Evento = new HashSet<Evento>();
        }
    
        public int ID { get; set; }
        public string Titulo { get; set; }
        public System.DateTime FechaNotificacion { get; set; }
        public string HoraNotificacion { get; set; }
        public int Tipo { get; set; }
        public bool Activa { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Caballo_ID { get; set; }
    
        public virtual ICollection<AlertaCaballo> AlertaCaballo { get; set; }
        public virtual Caballo Caballo { get; set; }
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
