//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caballo
    {
        public Caballo()
        {
            this.Alimentacion1 = new HashSet<Alimentacion>();
            this.GrupoCaballo = new HashSet<GrupoCaballo>();
            this.EstabloCaballo = new HashSet<EstabloCaballo>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string NumeroChip { get; set; }
        public Nullable<int> NumeroFEI { get; set; }
        public Nullable<bool> EstadoFEI { get; set; }
        public string Protector { get; set; }
        public string Embocadura { get; set; }
        public string ExtrasDeCabezada { get; set; }
        public Nullable<bool> ADN { get; set; }
        public string NumeroId { get; set; }
        public Nullable<int> NumeroFEN { get; set; }
        public Nullable<bool> EstadoFEN { get; set; }
        public Nullable<int> Criador_ID { get; set; }
        public Nullable<int> Establecimiento_ID { get; set; }
        public Nullable<int> EstadoProvincia_Id { get; set; }
        public int Genero_ID { get; set; }
        public Nullable<int> Grupo_ID { get; set; }
        public Nullable<int> OtrasMarcas_ID { get; set; }
        public Nullable<int> Pedigree_ID { get; set; }
        public int Pelaje_ID { get; set; }
        public Nullable<int> PersonaACargo_ID { get; set; }
        public Nullable<int> Propietario_ID { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ICollection<Alimentacion> Alimentacion1 { get; set; }
        public virtual Criador Criador { get; set; }
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual EstadoProvincia EstadoProvincia { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual OtrasMarcas OtrasMarcas { get; set; }
        public virtual Pedigree Pedigree { get; set; }
        public virtual Pelaje Pelaje { get; set; }
        public virtual PersonaACargo PersonaACargo { get; set; }
        public virtual Propietario Propietario { get; set; }
        public virtual ICollection<GrupoCaballo> GrupoCaballo { get; set; }
        public virtual ICollection<EstabloCaballo> EstabloCaballo { get; set; }
    }
}
