//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionCorreo
    {
        public ConfiguracionCorreo()
        {
            this.PlantillaCorreo = new HashSet<PlantillaCorreo>();
        }
    
        public int ID { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public string Host { get; set; }
        public string Puerto { get; set; }
        public bool EnableSsl { get; set; }
        public bool UseDefaultCredentials { get; set; }
    
        public virtual ICollection<PlantillaCorreo> PlantillaCorreo { get; set; }
    }
}
