//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoProvincia
    {
        public EstadoProvincia()
        {
            this.Caballo = new HashSet<Caballo>();
            this.Propietario = new HashSet<Propietario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Pais_ID { get; set; }
    
        public virtual ICollection<Caballo> Caballo { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Propietario> Propietario { get; set; }
    }
}
