//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoProvincia
    {
        public EstadoProvincia()
        {
            this.Caballo = new HashSet<Caballo>();
            this.Propietario = new HashSet<Propietario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Pais_ID { get; set; }
    
        public virtual ICollection<Caballo> Caballo { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Propietario> Propietario { get; set; }
    }
}
