//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstabloTelefono
    {
        public int ID { get; set; }
        public string Numero { get; set; }
        public int Tipo_Numero_ID { get; set; }
        public int Establo_ID { get; set; }
    
        public virtual Establo Establo { get; set; }
        public virtual Tipo_Numero Tipo_Numero { get; set; }
    }
}
