//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establo
    {
        public Establo()
        {
            this.EstabloCaballo = new HashSet<EstabloCaballo>();
            this.EstabloTelefono = new HashSet<EstabloTelefono>();
            this.EstabloCorreo = new HashSet<EstabloCorreo>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Manager { get; set; }
        public string Direccion { get; set; }
        public int Propietario_ID { get; set; }
    
        public virtual Propietario Propietario { get; set; }
        public virtual ICollection<EstabloCaballo> EstabloCaballo { get; set; }
        public virtual ICollection<EstabloTelefono> EstabloTelefono { get; set; }
        public virtual ICollection<EstabloCorreo> EstabloCorreo { get; set; }
    }
}
