//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establo
    {
        public Establo()
        {
            this.EstabloCaballo = new HashSet<EstabloCaballo>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Manager { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public int Propietario_ID { get; set; }
    
        public virtual Propietario Propietario { get; set; }
        public virtual ICollection<EstabloCaballo> EstabloCaballo { get; set; }
    }
}
