//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establecimiento
    {
        public Establecimiento()
        {
            this.Caballo = new HashSet<Caballo>();
            this.Mail_Establecimiento = new HashSet<Mail_Establecimiento>();
            this.Numero_Establecimiento = new HashSet<Numero_Establecimiento>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Propietario { get; set; }
        public string Ubicacion { get; set; }
        public string DescUbicacion { get; set; }
    
        public virtual ICollection<Caballo> Caballo { get; set; }
        public virtual ICollection<Mail_Establecimiento> Mail_Establecimiento { get; set; }
        public virtual ICollection<Numero_Establecimiento> Numero_Establecimiento { get; set; }
    }
}
