//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstabloCaballo
    {
        public int ID { get; set; }
        public int Establo_ID { get; set; }
        public int Caballo_ID { get; set; }
    
        public virtual Caballo Caballo { get; set; }
        public virtual Establo Establo { get; set; }
    }
}
