//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establecimiento
    {
        public Establecimiento()
        {
            this.Caballo = new HashSet<Caballo>();
            this.Mail_Establecimiento = new HashSet<Mail_Establecimiento>();
            this.Numero_Establecimiento = new HashSet<Numero_Establecimiento>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Propietario { get; set; }
        public string Ubicacion { get; set; }
        public string DescUbicacion { get; set; }
    
        public virtual ICollection<Caballo> Caballo { get; set; }
        public virtual ICollection<Mail_Establecimiento> Mail_Establecimiento { get; set; }
        public virtual ICollection<Numero_Establecimiento> Numero_Establecimiento { get; set; }
    }
}
