//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.Caballo = new HashSet<Caballo>();
            this.GrupoCaballo = new HashSet<GrupoCaballo>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Propietario_ID { get; set; }
        public Nullable<bool> GrupoDefault { get; set; }
    
        public virtual ICollection<Caballo> Caballo { get; set; }
        public virtual ICollection<GrupoCaballo> GrupoCaballo { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
