//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail_Establecimiento
    {
        public int ID { get; set; }
        public string MailDesc { get; set; }
        public Nullable<int> Establecimiento_ID { get; set; }
        public Nullable<int> Tipo_ID { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual Tipo_Mail Tipo_Mail { get; set; }
    }
}
