//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquilinkedEntities : DbContext
    {
        public EquilinkedEntities()
            : base("name=EquilinkedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Alerta> Alerta { get; set; }
        public virtual DbSet<AlertaCaballo> AlertaCaballo { get; set; }
        public virtual DbSet<Alimentacion> Alimentacion { get; set; }
        public virtual DbSet<Caballo> Caballo { get; set; }
        public virtual DbSet<Criador> Criador { get; set; }
        public virtual DbSet<Establecimiento> Establecimiento { get; set; }
        public virtual DbSet<EstadoProvincia> EstadoProvincia { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Mail_Establecimiento> Mail_Establecimiento { get; set; }
        public virtual DbSet<Numero_Establecimiento> Numero_Establecimiento { get; set; }
        public virtual DbSet<OtrasMarcas> OtrasMarcas { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pedigree> Pedigree { get; set; }
        public virtual DbSet<Pelaje> Pelaje { get; set; }
        public virtual DbSet<PersonaACargo> PersonaACargo { get; set; }
        public virtual DbSet<Propietario> Propietario { get; set; }
        public virtual DbSet<Tipo_Mail> Tipo_Mail { get; set; }
        public virtual DbSet<Tipo_Numero> Tipo_Numero { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<GrupoCaballo> GrupoCaballo { get; set; }
    }
}
