//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedigree
    {
        public Pedigree()
        {
            this.Caballo = new HashSet<Caballo>();
        }
    
        public int ID { get; set; }
        public string Padre { get; set; }
        public string Madre { get; set; }
        public string Imagen { get; set; }
    
        public virtual ICollection<Caballo> Caballo { get; set; }
    }
}
