//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equilinked.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Numero
    {
        public Tipo_Numero()
        {
            this.Numero_Establecimiento = new HashSet<Numero_Establecimiento>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Numero_Establecimiento> Numero_Establecimiento { get; set; }
    }
}
