CREATE TABLE AlertaGrupo (
	ID INT IDENTITY NOT NULL,
	Alerta_ID INT NOT NULL,
	Grupo_ID INT NOT NULL
)
GO

ALTER TABLE AlertaGrupo ADD CONSTRAINT PK_AlertaGrupo PRIMARY KEY(ID)
GO

ALTER TABLE AlertaGrupo ADD CONSTRAINT FK_AlertaGrupo_Alerta_ID FOREIGN KEY(Alerta_ID) REFERENCES Alerta(ID)
GO

ALTER TABLE AlertaGrupo ADD CONSTRAINT FK_AlertaGrupo_Grupo_ID FOREIGN KEY(Grupo_ID) REFERENCES Grupo(ID)
GO

ALTER TABLE Alerta ADD Ubicacion VARCHAR(255)
GO